-- Clinical Placements Database — full schema
--
-- Generated by introspecting the live Supabase database on 2026-07-15.
-- Running this against an empty Postgres database produces every table, index,
-- trigger and view the application queries. Structure only — see
-- docs/DATA_PIPELINE.md for loading the data.
--
-- Object inventory: 10 tables + 1 view.
--   layers, hrsa_sites, schools, post_secondary_schools, military_sites,
--   native_american_reserves, active_sites, county_population, state_economic,
--   notes, and the county_coverage view.
--
-- Keep this in sync when you change the database. A previous version of this
-- file defined only 7 of these objects, which meant the database could not be
-- rebuilt from a clone.

-- =============================================================================
-- TYPES AND FUNCTIONS
-- =============================================================================

-- schools.profession depends on this; create it before the tables.
CREATE TYPE profession_type AS ENUM ('PT', 'OT', 'PA');

-- Touches updated_at on write. Wired up as a BEFORE UPDATE trigger on the five
-- tables that are edited in place. The bulk-loaded tables (hrsa_sites,
-- active_sites) are truncated and reimported rather than updated, so they rely
-- on their column default instead.
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- =============================================================================
-- LAYERS — map layer metadata, drives the sidebar toggles (10 rows)
-- =============================================================================

CREATE TABLE layers (
  id              SERIAL PRIMARY KEY,
  layer_key       VARCHAR(50)  NOT NULL UNIQUE,
  display_name    VARCHAR(100) NOT NULL,
  table_name      VARCHAR(100) NOT NULL,
  description     TEXT,
  icon            VARCHAR(50),
  color           CHAR(7),
  default_visible BOOLEAN   DEFAULT FALSE,
  sort_order      INTEGER   DEFAULT 0,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_layers_layer_key ON layers (layer_key);

-- =============================================================================
-- HRSA_SITES — HRSA healthcare facilities (74,772 rows)
-- =============================================================================

CREATE TABLE hrsa_sites (
  id                       SERIAL PRIMARY KEY,
  site_name                TEXT,
  site_category            TEXT,
  state                    CHAR(2) NOT NULL,
  city                     TEXT,
  county_fips              CHAR(5),
  physician_ftes           NUMERIC(10,2) DEFAULT 0,
  physician_assistant_ftes NUMERIC(10,2) DEFAULT 0,
  num_beds                 INTEGER       DEFAULT 0,
  is_federally_funded_hc   BOOLEAN       DEFAULT FALSE,
  is_hospital_based        BOOLEAN       DEFAULT FALSE,
  site_type                TEXT,
  is_rural_health_clinic   BOOLEAN       DEFAULT FALSE,
  rural_status             TEXT,
  longitude                NUMERIC(11,7) NOT NULL,
  latitude                 NUMERIC(10,7) NOT NULL,
  source                   TEXT NOT NULL DEFAULT 'HRSA',
  created_at               TIMESTAMPTZ DEFAULT NOW(),
  updated_at               TIMESTAMPTZ DEFAULT NOW()
);

-- idx_hrsa_coords backs the viewport-bounds filter in /api/sites and
-- idx_hrsa_category backs the clinic-type filter. Both matter at this row count.
CREATE INDEX idx_hrsa_state        ON hrsa_sites (state);
CREATE INDEX idx_hrsa_coords       ON hrsa_sites (latitude, longitude);
CREATE INDEX idx_hrsa_category     ON hrsa_sites (site_category);
CREATE INDEX idx_hrsa_city         ON hrsa_sites (city);
CREATE INDEX idx_hrsa_fips         ON hrsa_sites (county_fips);
CREATE INDEX idx_hrsa_fqhc         ON hrsa_sites (is_federally_funded_hc);
CREATE INDEX idx_hrsa_name         ON hrsa_sites (site_name);
CREATE INDEX idx_hrsa_rural        ON hrsa_sites (is_rural_health_clinic);
CREATE INDEX idx_hrsa_rural_status ON hrsa_sites (rural_status);

-- =============================================================================
-- SCHOOLS — PT/OT/PA programs (858 rows across 655 institutions)
-- =============================================================================
-- One row per PROGRAM, not per institution: a university offering PT, OT and PA
-- occupies three rows sharing an institution_name. Group by institution before
-- display — /api/sites does this to produce one map marker per campus.
--
-- There are no outcome columns (graduation / licensure pass / employment
-- rates). That data was never collected. See docs/DATABASE.md.

CREATE TABLE schools (
  id                   SERIAL PRIMARY KEY,
  program_row_id       INTEGER,
  institution_name     VARCHAR(300) NOT NULL,
  campus_name          VARCHAR(200),
  state                CHAR(2) NOT NULL,
  profession           profession_type NOT NULL,
  program_name         VARCHAR(200),
  accreditation_body   VARCHAR(20),
  accreditation_status VARCHAR(200),
  address              VARCHAR(500),
  longitude            NUMERIC(11,7),
  latitude             NUMERIC(10,7),
  source               VARCHAR(50),
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_schools_state            ON schools (state);
CREATE INDEX idx_schools_profession       ON schools (profession);
CREATE INDEX idx_schools_state_profession ON schools (state, profession);
CREATE INDEX idx_schools_coords           ON schools (latitude, longitude);
CREATE INDEX idx_schools_name             ON schools (institution_name);

CREATE TRIGGER update_schools_updated_at BEFORE UPDATE ON schools
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- POST_SECONDARY_SCHOOLS — all US post-secondary institutions (6,812 rows)
-- =============================================================================

CREATE TABLE post_secondary_schools (
  id               SERIAL PRIMARY KEY,
  original_id      INTEGER,
  institution_name VARCHAR(300) NOT NULL,
  state            CHAR(2) NOT NULL,
  latitude         NUMERIC(10,7),
  longitude        NUMERIC(11,7),
  source           VARCHAR(50),
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_post_secondary_state  ON post_secondary_schools (state);
CREATE INDEX idx_post_secondary_coords ON post_secondary_schools (latitude, longitude);
CREATE INDEX idx_post_secondary_name   ON post_secondary_schools (institution_name);

CREATE TRIGGER update_post_secondary_updated_at BEFORE UPDATE ON post_secondary_schools
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- MILITARY_SITES — US military installations (824 rows)
-- =============================================================================

CREATE TABLE military_sites (
  id         SERIAL PRIMARY KEY,
  name       VARCHAR(300) NOT NULL,
  state      CHAR(2) NOT NULL,
  component  VARCHAR(50),
  longitude  NUMERIC(11,7),
  latitude   NUMERIC(10,7),
  source     VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_military_state  ON military_sites (state);
CREATE INDEX idx_military_coords ON military_sites (latitude, longitude);
CREATE INDEX idx_military_name   ON military_sites (name);

CREATE TRIGGER update_military_updated_at BEFORE UPDATE ON military_sites
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- NATIVE_AMERICAN_RESERVES — tribal reservation locations (693 rows)
-- =============================================================================

CREATE TABLE native_american_reserves (
  id         SERIAL PRIMARY KEY,
  name       VARCHAR(500) NOT NULL,
  state      CHAR(2) NOT NULL,
  latitude   NUMERIC(10,7),
  longitude  NUMERIC(11,7),
  source     VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_native_american_state  ON native_american_reserves (state);
CREATE INDEX idx_native_american_coords ON native_american_reserves (latitude, longitude);
CREATE INDEX idx_native_american_name   ON native_american_reserves (name);

CREATE TRIGGER update_native_american_updated_at BEFORE UPDATE ON native_american_reserves
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- ACTIVE_SITES — Clarkson's current clinical placement sites (805 rows)
-- =============================================================================
-- Sourced from Exxat. Unlike schools, program membership is denormalised into
-- the has_ot / has_pt / has_pa booleans, so there is one row per site.

CREATE TABLE active_sites (
  id         SERIAL PRIMARY KEY,
  site_name  TEXT NOT NULL,
  address    TEXT,
  city       TEXT,
  state      TEXT,
  programs   TEXT,
  has_ot     BOOLEAN DEFAULT FALSE,
  has_pt     BOOLEAN DEFAULT FALSE,
  has_pa     BOOLEAN DEFAULT FALSE,
  longitude  NUMERIC(11,7) NOT NULL,
  latitude   NUMERIC(10,7) NOT NULL,
  source     TEXT NOT NULL DEFAULT 'Exxat Active Sites',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_active_state    ON active_sites (state);
CREATE INDEX idx_active_coords   ON active_sites (latitude, longitude);
CREATE INDEX idx_active_name     ON active_sites (site_name);
CREATE INDEX idx_active_programs ON active_sites (has_ot, has_pt, has_pa);

-- =============================================================================
-- COUNTY_POPULATION — Census county estimates (3,144 rows)
-- =============================================================================

CREATE TABLE county_population (
  id             SERIAL PRIMARY KEY,
  fips           CHAR(5) NOT NULL UNIQUE,
  county_name    TEXT NOT NULL,
  state_fips     CHAR(2) NOT NULL,
  state          CHAR(2) NOT NULL,
  pop_current    INTEGER NOT NULL,
  pop_previous   INTEGER NOT NULL,
  pop_change_pct NUMERIC(6,2),
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_countypop_fips   ON county_population (fips);
CREATE INDEX idx_countypop_state  ON county_population (state);
CREATE INDEX idx_countypop_change ON county_population (pop_change_pct);

-- =============================================================================
-- STATE_ECONOMIC — BEA GDP + BLS QCEW healthcare employment (51 rows)
-- =============================================================================

CREATE TABLE state_economic (
  id                         SERIAL PRIMARY KEY,
  state_fips                 CHAR(2) NOT NULL UNIQUE,
  state                      CHAR(2) NOT NULL,
  state_name                 TEXT NOT NULL,
  gdp_current                NUMERIC(15,1),
  gdp_previous               NUMERIC(15,1),
  gdp_change_pct             NUMERIC(6,2),
  gdp_year                   INTEGER,
  healthcare_employment      INTEGER,
  total_employment           INTEGER,
  healthcare_share_pct       NUMERIC(5,2),
  avg_healthcare_weekly_wage NUMERIC(8,2),
  employment_year            INTEGER,
  source                     TEXT NOT NULL DEFAULT 'BEA + BLS QCEW',
  created_at                 TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_state_econ_fips  ON state_economic (state_fips);
CREATE INDEX idx_state_econ_state ON state_economic (state);
CREATE INDEX idx_state_econ_gdp   ON state_economic (gdp_change_pct);
CREATE INDEX idx_state_econ_hc    ON state_economic (healthcare_share_pct);

-- =============================================================================
-- NOTES — unused (0 rows)
-- =============================================================================
-- Created for a site-annotation feature that was never built: no application
-- code reads or writes it, and the /api/notes route that once backed it has
-- been removed. Kept here so this file matches the live database. Safe to drop
-- if you are sure you don't want the feature.

CREATE TABLE notes (
  id         SERIAL PRIMARY KEY,
  layer_key  VARCHAR(50),
  entity_id  INTEGER,
  state      CHAR(2),
  note_text  TEXT NOT NULL,
  author     VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notes_layer_entity ON notes (layer_key, entity_id);
CREATE INDEX idx_notes_state        ON notes (state);

CREATE TRIGGER update_notes_updated_at BEFORE UPDATE ON notes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- COUNTY_COVERAGE (VIEW) — people per healthcare facility, by county
-- =============================================================================
-- Powers the "Healthcare Coverage" choropleth.
--
-- METHODOLOGY: the join counts only the facility-based HRSA categories listed
-- below. Categories such as Home Health Agency and Hospice are deliberately
-- excluded — they deliver care in the patient's home and have no fixed site a
-- student could be placed at, so counting them would overstate coverage.
--
-- people_per_facility is NULL rather than 0 where a county has no qualifying
-- facility. The frontend renders that as "no coverage" and it is the number
-- behind the "counties with zero facilities" figure.

CREATE VIEW county_coverage AS
SELECT
  cp.fips,
  cp.county_name,
  cp.state_fips,
  cp.state,
  cp.pop_current,
  cp.pop_previous,
  cp.pop_change_pct,
  count(h.id) AS facility_count,
  CASE
    WHEN count(h.id) > 0
      THEN round(cp.pop_current::numeric / count(h.id)::numeric, 0)
    ELSE NULL::numeric
  END AS people_per_facility
FROM county_population cp
LEFT JOIN hrsa_sites h
  ON h.county_fips = cp.fips
 AND h.site_category = ANY (ARRAY[
       'Hospital',
       'Ambulatory Surgical Center',
       'Comprehensive Outpatient Rehab Facility',
       'Outpatient Physical Therapy/Speech Pathology',
       'Federally Qualified Health Center',
       'Rural Health Clinic',
       'Community Mental Health Center',
       'Skilled Nursing Facility',
       'Skilled Nursing Facilities/Nursing Facility (Distinct Part)',
       'Skilled Nursing Facilities/Nursing Facility (Dually Certified)',
       'Nursing Facility'
     ])
GROUP BY cp.fips, cp.county_name, cp.state_fips, cp.state,
         cp.pop_current, cp.pop_previous, cp.pop_change_pct;
